---
language: bash
services: docker

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

script:
  - docker build -t cron:build .
  - ~/official-images/test/run.sh cron:build

after_script:
  - docker images
